import Head from 'next/head'
import React from 'react';
import Main from '../components/main'
import Services from '../components/services'
import Destination from '../components/destination';
import Trip from '../components/trip';
import About from '../components/about';
import Subscribe from '../components/subscribe';
import Footer from '../components/footer';


export default function Home() {
  return (
    <>
      <Head>
        <title>Jadoo Travel Agency</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/Jadoo.png" />
      </Head>

      <React.Fragment>
        <Main />
        <Services />
        <Destination />
        <Trip />
        <About />
        <Subscribe />
        <Footer />
      </React.Fragment>
    </>
  )
}
